/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as RouteCheckRouteImport } from './routes/route-check'
import { Route as RekomendasiRouteImport } from './routes/rekomendasi'
import { Route as HistorisRouteImport } from './routes/historis'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteCheckRoute = RouteCheckRouteImport.update({
  id: '/route-check',
  path: '/route-check',
  getParentRoute: () => rootRouteImport,
} as any)
const RekomendasiRoute = RekomendasiRouteImport.update({
  id: '/rekomendasi',
  path: '/rekomendasi',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorisRoute = HistorisRouteImport.update({
  id: '/historis',
  path: '/historis',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/historis': typeof HistorisRoute
  '/rekomendasi': typeof RekomendasiRoute
  '/route-check': typeof RouteCheckRoute
  '/tentang': typeof TentangRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/historis': typeof HistorisRoute
  '/rekomendasi': typeof RekomendasiRoute
  '/route-check': typeof RouteCheckRoute
  '/tentang': typeof TentangRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/historis': typeof HistorisRoute
  '/rekomendasi': typeof RekomendasiRoute
  '/route-check': typeof RouteCheckRoute
  '/tentang': typeof TentangRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/historis'
    | '/rekomendasi'
    | '/route-check'
    | '/tentang'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/historis'
    | '/rekomendasi'
    | '/route-check'
    | '/tentang'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/historis'
    | '/rekomendasi'
    | '/route-check'
    | '/tentang'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HistorisRoute: typeof HistorisRoute
  RekomendasiRoute: typeof RekomendasiRoute
  RouteCheckRoute: typeof RouteCheckRoute
  TentangRoute: typeof TentangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-check': {
      id: '/route-check'
      path: '/route-check'
      fullPath: '/route-check'
      preLoaderRoute: typeof RouteCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rekomendasi': {
      id: '/rekomendasi'
      path: '/rekomendasi'
      fullPath: '/rekomendasi'
      preLoaderRoute: typeof RekomendasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historis': {
      id: '/historis'
      path: '/historis'
      fullPath: '/historis'
      preLoaderRoute: typeof HistorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HistorisRoute: HistorisRoute,
  RekomendasiRoute: RekomendasiRoute,
  RouteCheckRoute: RouteCheckRoute,
  TentangRoute: TentangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
